{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [24/May/2022 14:49:09] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:09] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:09] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:10] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py:796: UndefinedMetricWarning:\n",
      "\n",
      "R^2 score is not well-defined with less than two samples.\n",
      "\n",
      "127.0.0.1 - - [24/May/2022 14:49:10] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:12] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:12] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:16] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:16] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:16] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:19] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:22] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:29] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:30] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:30] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:34] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:35] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:36] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:37] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:41] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:45] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:49] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:50] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:52] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:54] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:49:58] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:49:58] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:01] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:03] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:05] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:05] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:11] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:15] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:15] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:17] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:18] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:22] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:24] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:25] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:28] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in display_output\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\pandas\\core\\series.py\", line 3848, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 69, in <lambda>\n",
      "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 967, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 902, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-2-eae8aa43f9b4>\", line 71, in display_output\n",
      "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 663, in fit\n",
      "    X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\base.py\", line 581, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 979, in check_X_y\n",
      "    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)\n",
      "  File \"C:\\Users\\Alastair Tyson\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 997, in _check_y\n",
      "    y = y.astype(np.float64)\n",
      "ValueError: could not convert string to float: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/May/2022 14:50:30] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/May/2022 14:50:32] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/May/2022 14:53:50] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import dash\n",
    "import flask\n",
    "import math\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output, State\n",
    "import plotly.graph_objs as go\n",
    "import dash_table\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "\n",
    "app = dash.Dash(__name__)\n",
    "app.scripts.config.serve_locally = True\n",
    "\n",
    "app.layout=html.Div(children=[\n",
    "            html.H1(id='header',children=['Linear Regression Demonstration'],style={\n",
    "                              'textAlign': 'center',\n",
    "                              'color': 'blue',\n",
    "                              'fontSize':50}),\n",
    "            html.Div(id='instructions',\n",
    "                     children=['Enter coordinates in table below and watch as Linear Regression model find the line of best fit',\n",
    "                                                html.Br(),'You can select different metrics to see how the model performs'],\n",
    "                    style={'textAlign': 'center',\n",
    "                              'color': 'skyblue',\n",
    "                              'fontSize':20}              \n",
    "                    ),\n",
    "            dcc.Graph(id='adding-rows-graph'),\n",
    "            dcc.RadioItems(id='residuals',options=[{'label':'Residuals Off','value':'no'},\n",
    "                                                   {'label':'Residuals On','value':'yes'}],value='no'),\n",
    "            dcc.RadioItems(id='mean',options=[{'label':'Mean Off','value':'no'},\n",
    "                                              {'label':'Mean On','value':'yes'}],value='no'),\n",
    "            html.Br(),\n",
    "            html.Div(id='metrics'),\n",
    "            html.Br(),\n",
    "            html.Div(id='input',children=[\n",
    "                \n",
    "            \n",
    "                dash_table.DataTable(id='table', columns=[{'name':'x','id':'x','type':'numeric'},\n",
    "                                                      {'name':'y','id':'y','type':'numeric'}],\n",
    "                                             data=[{'x':5,'y':6}],\n",
    "                                             editable=True,\n",
    "                                             row_deletable=True),\n",
    "                html.Button('Add Row', id='editing-rows-button', n_clicks=0)\n",
    "                    ])\n",
    "            \n",
    "])   \n",
    "\n",
    "@app.callback(\n",
    "    Output('table', 'data'),\n",
    "    [Input('editing-rows-button', 'n_clicks')],\n",
    "    [State('table', 'data'),\n",
    "     State('table', 'columns')])\n",
    "def add_row(n_clicks, rows, columns):\n",
    "    if n_clicks > 0:\n",
    "        rows.append({c['id']: '' for c in columns})\n",
    "    return rows \n",
    "@app.callback(\n",
    "    [Output('adding-rows-graph', 'figure'),\n",
    "     Output('metrics','children')],\n",
    "    [Input('table', 'data'),\n",
    "     Input('table', 'columns'),\n",
    "     Input('residuals','value'),\n",
    "     Input('mean','value')])\n",
    "def display_output(rows, columns,resid,mean):\n",
    "    df = pd.DataFrame(rows, columns=[c['name'] for c in columns])\n",
    "    df['rd']=df.x.apply(lambda x: int(round(float(x),0)))\n",
    "    x=[i for i in range(df.rd.max()+2)]\n",
    "    mod=LinearRegression().fit(df[['x']],df[['y']])\n",
    "    df['pred']=mod.predict(df[['x']])\n",
    "    r2=mod.score(df[['x']],df[['y']])\n",
    "    mae=mean_absolute_error(df[['y']],df[['pred']])\n",
    "    rmse=mean_squared_error(df[['y']],df[['pred']])**0.5\n",
    "    if mean=='yes':\n",
    "        mn=df.y.mean()\n",
    "    else:\n",
    "        mn=[]\n",
    "    children=['R^2 Score: ' + str(r2),html.Br(),'Mean Absolute Error: ' +str(mae),html.Br(),'Root Mean Squared Error: '+str(rmse)]\n",
    "    fig=go.Figure()\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=[i for i in df['x']],\n",
    "        y=[j for j in df['y']],\n",
    "        mode='markers',\n",
    "        showlegend=False\n",
    "    )),\n",
    "    fig.add_trace(go.Scatter(\n",
    "        name='Regression Line',\n",
    "        x=[i for i in x],\n",
    "        y=[mod.intercept_[0]+mod.coef_[0][0]*x[i] for i in x],\n",
    "       \n",
    "    )),\n",
    "    fig.add_trace(go.Scatter(\n",
    "        name='Mean Line',\n",
    "        x=[i for i in x],\n",
    "        y=[mn for i in range(df.rd.max()+2)],\n",
    "       \n",
    "    )),\n",
    "    if resid=='yes':\n",
    "        for index in range(len(df.x)):\n",
    "            if df.y[index]>df.pred[index]:\n",
    "                fig.add_shape(\n",
    "                    dict(type='line',x0=df.x[index],y0=df.pred[index],x1=df.x[index],y1=df.y[index]))\n",
    "            else:\n",
    "                fig.add_shape(\n",
    "                    dict(type='line',x0=df.x[index],y0=df.y[index],x1=df.x[index],y1=df.pred[index]))   \n",
    "      \n",
    "    return fig,children\n",
    "                                   \n",
    "                                   \n",
    "            \n",
    "\n",
    "application=app.server\n",
    "if __name__ == '__main__':\n",
    "    \n",
    "    application.run(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
